### ISSUE TITLE
AHK Error when Loading/Refreshing skin

### ISSUE THREAD

**Issue by Stewie410** [jonseppanen/wwing#1]
Hello, I've just installed the wwing skin, and am experiencing a couple of bugs:

When Launching Rainmeter/Wwing, an error window appears, as attached below: 
![screenshot_1](https://user-images.githubusercontent.com/24593067/35186750-396c3a1a-fde7-11e7-9824-7987ce6e4265.png)

I thought perhaps the regex declaration didn't need to be quoted, but that caused a far more OTT error.  For reference, I've also opted to use Raindock as the dock rather than Winstep Nexus.

**Comment by jonseppanen** [comment]
that's very strange, it looks like AHK v1 code, but I write and use AHK v2.

Are you running specifically AHK v2?

**Comment by Stewie410** [comment]
For compatibility reasons, I've got both AHK v2 and the stable release installed on my machine; though as noted in the instructions, v2 is the only one running as far as I know.  Compatibility reasons = if I need to write some scripts for work, I tend to opt for the old one because of the varying hardware/software...but I can remove those if that's the (probable) culprit.

![screenshot_1](https://user-images.githubusercontent.com/24593067/35191756-3b82e8a2-fe51-11e7-9b94-a7ac75347286.png)

AHKU32 and AHKU64, highlighted in red, are the AHKv2 execs, amongst the plethora of other ones.

**Comment by jonseppanen** [comment]
This is the issue. In the next few hours I will write an update that removes the ahkv2 requirement and a few bug fixes. Keep an eye out.

In the meantime, kill the wwing script, then go to its folder, right click the wwing.ahk -> run with -> ahk v2 exe file.

**Comment by Stewie410** [comment]
Ahh, you were right.  As you suggested, I set wwing.ahk to run with AHKv2, but the same error kept appearing.  Removing the stable release of AHK (such that AHKv2 was the only one left) seems to have corrected the error.
It should also be noted that the error also prevented the overlays from triggering properly, as well as hiding the taskbar correctly, after getting around that.

**Comment by jonseppanen** [comment]
A majority of the theme's logic is coded in AHK, as AHK is much faster than rainmeter for most things. This means the theme is super fast.

Overlays and taskbar hide, as well as min/max display are all done in AHK for this reason, for optimum speed.

**Comment by jonseppanen** [comment]
I have removed the AHK requirement, and bundled it within the skin instead.
