### ISSUE TITLE
AHK does nothing

### ISSUE THREAD

**Issue by nodgear** [jonseppanen/wwing#4]
I'm using AHK V2, without V1 installed.
I need to open wwing.ahk manually, it runs but does nothing.

My wwing doesn't change color, doesn't detect downloads (using chrome, .crdownload files)
My steam icon doesn't do anything.
What i need to do?
![ahk](https://user-images.githubusercontent.com/22383863/36075407-712c9ec0-0f2d-11e8-9b78-d1f40f2d7ee4.png)

**Comment by nodgear** [comment]
The nylas icon is from my Nexusdock, i didn't modify the skin

**Comment by jonseppanen** [comment]
What kind of rainmeter install do you have?

**Comment by nodgear** [comment]
4.0.2 Version - Windows 10 x64
My log screenshot:
![image](https://user-images.githubusercontent.com/22383863/36082656-3037ccf2-0f8a-11e8-8020-6d2f8904c3fa.png)

**Comment by nodgear** [comment]
4.0.2 installation (normal)
Fixed: started background.ini manually and setting above wwing works fine.
But my steam buttons doesn't work at all, i have my userid in variables.
![image](https://user-images.githubusercontent.com/22383863/36083635-48bc7cba-0f93-11e8-987a-56f0ada7c853.png)
Network and volume overlays working like a charm.
![image](https://user-images.githubusercontent.com/22383863/36083641-5b60e54a-0f93-11e8-9daa-243a9ea748f8.png)

Is there any file to translate wheater texts?

**Comment by jonseppanen** [comment]
Make sure the full steam ID will resolve to your steam friend list in a web browser, AND your steam profile is PUBLIC.

Let me know how you go

**Comment by nodgear** [comment]
Public profile: Check;
Full steam ID on variables: Check;
![image](https://user-images.githubusercontent.com/22383863/36087645-3523ff42-0fb2-11e8-872b-f5ce0b097ada.png)

![image](https://user-images.githubusercontent.com/22383863/36087611-09fd1222-0fb2-11e8-8648-afc1176a0d3f.png)

![image](https://user-images.githubusercontent.com/22383863/36087660-4822533c-0fb2-11e8-86e4-afaa977e1ec2.png)

**Comment by nodgear** [comment]
Public profile: Check;
Full steam ID on variables: Check;
![image](https://user-images.githubusercontent.com/22383863/36087645-3523ff42-0fb2-11e8-872b-f5ce0b097ada.png)

![image](https://user-images.githubusercontent.com/22383863/36087611-09fd1222-0fb2-11e8-8648-afc1176a0d3f.png)
![image](https://user-images.githubusercontent.com/22383863/36087749-a778717c-0fb2-11e8-949c-8af2e42edb2c.png)


![image](https://user-images.githubusercontent.com/22383863/36087660-4822533c-0fb2-11e8-86e4-afaa977e1ec2.png)

This woks after 40 minutes AFK, no reasons  👍 
I think rainmeter just doesn't refresh the variables for some reason...
