### ISSUE TITLE
Non-issue, ahk v2 installation

### ISSUE THREAD

**Issue by alirng** [jonseppanen/wwing#7]
Hey, I know this is kind of stupid but I've been trying to install ahk 2.0 without any luck. There are hardly any guides online and the few that are available aren't very informative. So I was wondering if you had compiled the files to an exe installer that was talked about. I really want to get this to work as it looks amazing and pairs perfectly with your dock.

Thanks.

**Comment by nodgear** [comment]
You don't need to install AHK
just extract somewhere, select a ahk file and point the .exe inside folder (check the box to always open with that)

The new testing version (from github branch) alredy have compiled files, but some bugs too.
