### ISSUE TITLE
Error: Parameter #1 invalid.

### ISSUE THREAD

**Issue by yolo-spolo** [jonseppanen/wwing#8]
after starting rainmeter i get this error -->
![image](https://user-images.githubusercontent.com/25101621/46549861-0c541f00-c8dc-11e8-8bb8-dbcfb3d6f006.png)
after a couple of seconds rainmeter closes

**Comment by nodgear** [comment]
You're missing AHK

**Comment by nodgear** [comment]
Old issue, if you somehow got the same message:
Use the wwing.exe binary as default for ahk scripts (@Resoures/Utils/wwing.exe)
