### ISSUE TITLE
Requesting contributor role.

### ISSUE THREAD

**Issue by nodgear** [jonseppanen/wwing#9]
Hello, i've been using WWING since posted on Deviantart, leading me to build my own project using some of your functions. [My project](https://github.com/nodgear/Awesome)
But i still think WWING has it's place, so i'm requesting contributor role to commit and manage issues on WWING.

**Comment by jonseppanen** [comment]
Hi Nodgear,

I have fully switched over to linux so I do not use rainmeter any more... at least until windows decide to strip out all of the bloat it currently has.

More than happy to set you up. Will do shortly.

**Comment by nodgear** [comment]
Hello again, and thx.
I'm also a linux user (using it while doing this comment), but because of work reasons i have to use windows specific software.

I'll be happily pushing commits to wwing at the end of this week :)
Issue closed, i'm now a participant.

**Comment by nodgear** [comment]
Update on why i ended up not making a new release of WWING:
Cariboudjan released Droptop, replacing WWING on almost every feature, i got filled up with microsoft shit over time and ended up dropping windows as a whole.

Recently (as in few months ago) i had to install windows again and to make [my own topbar, based in react and web tech](https://www.deviantart.com/nodgear/art/Hyper-dev-showcase-2-899660238) - [demonstration](https://i.wisp.run/f/sCmAtH.mp4)

Received an update about your react project and decided to come here to get it clean. See you around//
